// <auto-generated />
using System;
using Examen.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Analyse", b =>
                {
                    b.Property<int>("AnalyseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalyseId"));

                    b.Property<int>("DureeResultat")
                        .HasColumnType("int");

                    b.Property<int>("LaboratoireId")
                        .HasColumnType("int");

                    b.Property<double>("PrixAnalyse")
                        .HasColumnType("float");

                    b.Property<string>("TypeAnalyse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ValeurAnalyse")
                        .HasColumnType("real");

                    b.Property<float>("ValeurMaxNormale")
                        .HasColumnType("real");

                    b.Property<float>("ValeurMinNormale")
                        .HasColumnType("real");

                    b.HasKey("AnalyseId");

                    b.ToTable("Analyses");

                    b.HasData(
                        new
                        {
                            AnalyseId = 1,
                            DureeResultat = 24,
                            LaboratoireId = 1,
                            PrixAnalyse = 50.0,
                            TypeAnalyse = "Numération globulaire",
                            ValeurAnalyse = 4.8f,
                            ValeurMaxNormale = 5.5f,
                            ValeurMinNormale = 4f
                        });
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Bilan", b =>
                {
                    b.Property<int>("InfirmierId")
                        .HasColumnType("int");

                    b.Property<string>("CodePatient")
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DatePrelevement")
                        .HasColumnType("datetime2");

                    b.Property<int>("AnalyseId")
                        .HasColumnType("int");

                    b.Property<string>("EmailMedecin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Paye")
                        .HasColumnType("bit");

                    b.HasKey("InfirmierId", "CodePatient", "DatePrelevement");

                    b.HasIndex("AnalyseId");

                    b.HasIndex("CodePatient");

                    b.ToTable("Bilans");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Infirmier", b =>
                {
                    b.Property<int>("InfirmierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfirmierId"));

                    b.Property<int>("LaboratoireId")
                        .HasColumnType("int");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Specialite")
                        .HasColumnType("int");

                    b.HasKey("InfirmierId");

                    b.HasIndex("LaboratoireId");

                    b.ToTable("Infirmiers");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Laboratoire", b =>
                {
                    b.Property<int>("LaboratoireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaboratoireId"));

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LaboratoireId");

                    b.ToTable("Laboratoires");

                    b.HasData(
                        new
                        {
                            LaboratoireId = 1,
                            Intitule = "Laboratoire Central",
                            Localisation = "Centre-ville"
                        });
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Patient", b =>
                {
                    b.Property<string>("CodePatient")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EmailPatient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Informations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodePatient");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            CodePatient = "P0001",
                            EmailPatient = "sarra@example.tn",
                            Informations = "Aucune",
                            NomComplet = "Sarra Trabelsi",
                            NumeroTel = "99887766"
                        });
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Bilan", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Analyse", "Analyse")
                        .WithMany("Bilans")
                        .HasForeignKey("AnalyseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.Patient", "Patient")
                        .WithMany("Bilans")
                        .HasForeignKey("CodePatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.Infirmier", "Infirmier")
                        .WithMany("Bilans")
                        .HasForeignKey("InfirmierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analyse");

                    b.Navigation("Infirmier");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Infirmier", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Laboratoire", "Laboratoire")
                        .WithMany("Infirmiers")
                        .HasForeignKey("LaboratoireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratoire");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Analyse", b =>
                {
                    b.Navigation("Bilans");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Infirmier", b =>
                {
                    b.Navigation("Bilans");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Laboratoire", b =>
                {
                    b.Navigation("Infirmiers");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Patient", b =>
                {
                    b.Navigation("Bilans");
                });
#pragma warning restore 612, 618
        }
    }
}
